/* eslint-disable */
// This file is generated by GraphQL Code Generator. Do not edit directly.
import type { GraphQLResolveInfo, GraphQLScalarType, GraphQLScalarTypeConfig } from 'graphql';
import type { Book, ChatMessage, Rating, Review, User } from '@prisma/client';
import type { GraphQLContext } from './context.js';

export type Maybe<T> = T | null;
export type InputMaybe<T> = Maybe<T>;
export type Exact<T extends { [key: string]: unknown }> = { [K in keyof T]: T[K] };
export type MakeOptional<T, K extends keyof T> = Omit<T, K> & { [SubKey in K]?: Maybe<T[SubKey]> };
export type MakeMaybe<T, K extends keyof T> = Omit<T, K> & { [SubKey in K]: Maybe<T[SubKey]> };

export type Scalars = {
  ID: { input: string; output: string };
  String: { input: string; output: string };
  Boolean: { input: boolean; output: boolean };
  Int: { input: number; output: number };
  Float: { input: number; output: number };
  DateTime: { input: Date; output: Date };
};

export type AddReviewInput = {
  bookId: Scalars['ID']['input'];
  body: Scalars['String']['input'];
  score?: InputMaybe<Scalars['Int']['input']>;
};

export type AuthPayload = {
  __typename?: 'AuthPayload';
  token: Scalars['String']['output'];
  user: User;
};

export type BookConnection = {
  __typename?: 'BookConnection';
  edges: Array<BookEdge>;
  pageInfo: PageInfo;
};

export type BookEdge = {
  __typename?: 'BookEdge';
  cursor: Scalars['String']['output'];
  node: Book;
};

export type ChatMessageConnection = {
  __typename?: 'ChatMessageConnection';
  edges: Array<ChatMessageEdge>;
  pageInfo: PageInfo;
};

export type ChatMessageEdge = {
  __typename?: 'ChatMessageEdge';
  cursor: Scalars['String']['output'];
  node: ChatMessage;
};

export type CreateBookInput = {
  author: Scalars['String']['input'];
  coverUrl?: InputMaybe<Scalars['String']['input']>;
  description: Scalars['String']['input'];
  genre: Scalars['String']['input'];
  title: Scalars['String']['input'];
};

export type LoginInput = {
  email: Scalars['String']['input'];
  password: Scalars['String']['input'];
};

export type PageInfo = {
  __typename?: 'PageInfo';
  endCursor?: Maybe<Scalars['String']['output']>;
  hasNextPage: Scalars['Boolean']['output'];
};

export type RegisterInput = {
  email: Scalars['String']['input'];
  name: Scalars['String']['input'];
  password: Scalars['String']['input'];
};

export type ReviewConnection = {
  __typename?: 'ReviewConnection';
  edges: Array<ReviewEdge>;
  pageInfo: PageInfo;
};

export type ReviewEdge = {
  __typename?: 'ReviewEdge';
  cursor: Scalars['String']['output'];
  node: Review;
};

export type SendChatMessageInput = {
  bookId: Scalars['ID']['input'];
  message: Scalars['String']['input'];
};

export type BookReviewsArgs = {
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Int']['input']>;
};

export type QueryBooksArgs = {
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Int']['input']>;
  search?: InputMaybe<Scalars['String']['input']>;
};

export type QueryBookArgs = {
  id: Scalars['ID']['input'];
};

export type QueryChatMessagesArgs = {
  after?: InputMaybe<Scalars['String']['input']>;
  bookId: Scalars['ID']['input'];
  first?: InputMaybe<Scalars['Int']['input']>;
};

export type QueryRecommendationsArgs = {
  limit?: InputMaybe<Scalars['Int']['input']>;
};

export type MutationAddReviewArgs = {
  input: AddReviewInput;
};

export type MutationCreateBookArgs = {
  input: CreateBookInput;
};

export type MutationLoginArgs = {
  input: LoginInput;
};

export type MutationRegisterArgs = {
  input: RegisterInput;
};

export type MutationSendChatMessageArgs = {
  input: SendChatMessageInput;
};

export type SubscriptionChatMessageAddedArgs = {
  bookId: Scalars['ID']['input'];
};

export type ResolverTypeWrapper<T> = Promise<T> | T;

export type ResolversTypes = {
  AddReviewInput: AddReviewInput;
  AuthPayload: ResolverTypeWrapper<AuthPayload>;
  Boolean: ResolverTypeWrapper<Scalars['Boolean']['output']>;
  Book: ResolverTypeWrapper<Book>;
  BookConnection: ResolverTypeWrapper<BookConnection>;
  BookEdge: ResolverTypeWrapper<BookEdge>;
  ChatMessage: ResolverTypeWrapper<ChatMessage>;
  ChatMessageConnection: ResolverTypeWrapper<ChatMessageConnection>;
  ChatMessageEdge: ResolverTypeWrapper<ChatMessageEdge>;
  CreateBookInput: CreateBookInput;
  DateTime: ResolverTypeWrapper<Scalars['DateTime']['output']>;
  Float: ResolverTypeWrapper<Scalars['Float']['output']>;
  ID: ResolverTypeWrapper<Scalars['ID']['output']>;
  Int: ResolverTypeWrapper<Scalars['Int']['output']>;
  LoginInput: LoginInput;
  Mutation: ResolverTypeWrapper<Record<string, never>>;
  PageInfo: ResolverTypeWrapper<PageInfo>;
  Query: ResolverTypeWrapper<Record<string, never>>;
  Rating: ResolverTypeWrapper<Rating>;
  RegisterInput: RegisterInput;
  Review: ResolverTypeWrapper<Review>;
  ReviewConnection: ResolverTypeWrapper<ReviewConnection>;
  ReviewEdge: ResolverTypeWrapper<ReviewEdge>;
  SendChatMessageInput: SendChatMessageInput;
  String: ResolverTypeWrapper<Scalars['String']['output']>;
  Subscription: ResolverTypeWrapper<Record<string, never>>;
  User: ResolverTypeWrapper<User>;
};

export type ResolverFn<TResult, TParent = Record<string, never>, TContext = GraphQLContext, TArgs = Record<string, never>> = (
  parent: TParent,
  args: TArgs,
  context: TContext,
  info: GraphQLResolveInfo
) => Promise<TResult> | TResult;

export type SubscriptionSubscribeFn<TResult, TParent = Record<string, never>, TContext = GraphQLContext, TArgs = Record<string, never>> = (
  parent: TParent,
  args: TArgs,
  context: TContext,
  info: GraphQLResolveInfo
) => AsyncIterable<TResult> | Promise<AsyncIterable<TResult>>;

export type Resolver<TResult, TParent = Record<string, never>, TContext = GraphQLContext, TArgs = Record<string, never>> = ResolverFn<TResult, TParent, TContext, TArgs>;

export type SubscriptionResolver<TResult, TParent = Record<string, never>, TContext = GraphQLContext, TArgs = Record<string, never>> = {
  subscribe: SubscriptionSubscribeFn<TResult, TParent, TContext, TArgs>;
  resolve?: ResolverFn<TResult, TParent, TContext, TArgs>;
};

export type DateTimeScalarConfig = GraphQLScalarTypeConfig<Scalars['DateTime']['output'], Scalars['DateTime']['input']>;

export type QueryResolvers<ContextType = GraphQLContext> = {
  me?: Resolver<Maybe<User>, Record<string, never>, ContextType>;
  users?: Resolver<Array<User>, Record<string, never>, ContextType>;
  book?: Resolver<Maybe<Book>, Record<string, never>, ContextType, QueryBookArgs>;
  books?: Resolver<BookConnection, Record<string, never>, ContextType, QueryBooksArgs>;
  recommendations?: Resolver<Array<Book>, Record<string, never>, ContextType, QueryRecommendationsArgs>;
  chatMessages?: Resolver<ChatMessageConnection, Record<string, never>, ContextType, QueryChatMessagesArgs>;
};

export type MutationResolvers<ContextType = GraphQLContext> = {
  register?: Resolver<AuthPayload, Record<string, never>, ContextType, MutationRegisterArgs>;
  login?: Resolver<AuthPayload, Record<string, never>, ContextType, MutationLoginArgs>;
  createBook?: Resolver<Book, Record<string, never>, ContextType, MutationCreateBookArgs>;
  addReview?: Resolver<Review, Record<string, never>, ContextType, MutationAddReviewArgs>;
  sendChatMessage?: Resolver<ChatMessage, Record<string, never>, ContextType, MutationSendChatMessageArgs>;
};

export type SubscriptionResolvers<ContextType = GraphQLContext> = {
  chatMessageAdded?: SubscriptionResolver<ChatMessage, Record<string, never>, ContextType, SubscriptionChatMessageAddedArgs>;
};

export type UserResolvers<ContextType = GraphQLContext> = {
  id?: Resolver<Scalars['ID']['output'], User, ContextType>;
  name?: Resolver<Scalars['String']['output'], User, ContextType>;
  email?: Resolver<Scalars['String']['output'], User, ContextType>;
  avatarUrl?: Resolver<Maybe<Scalars['String']['output']>, User, ContextType>;
  books?: Resolver<Array<Book>, User, ContextType>;
  createdAt?: Resolver<Scalars['DateTime']['output'], User, ContextType>;
};

export type BookResolvers<ContextType = GraphQLContext> = {
  id?: Resolver<Scalars['ID']['output'], Book, ContextType>;
  title?: Resolver<Scalars['String']['output'], Book, ContextType>;
  author?: Resolver<Scalars['String']['output'], Book, ContextType>;
  description?: Resolver<Scalars['String']['output'], Book, ContextType>;
  coverUrl?: Resolver<Maybe<Scalars['String']['output']>, Book, ContextType>;
  genre?: Resolver<Scalars['String']['output'], Book, ContextType>;
  owner?: Resolver<User, Book, ContextType>;
  reviews?: Resolver<ReviewConnection, Book, ContextType, BookReviewsArgs>;
  ratings?: Resolver<Array<Rating>, Book, ContextType>;
  averageRating?: Resolver<Maybe<Scalars['Float']['output']>, Book, ContextType>;
  createdAt?: Resolver<Scalars['DateTime']['output'], Book, ContextType>;
};

export type ReviewResolvers<ContextType = GraphQLContext> = {
  id?: Resolver<Scalars['ID']['output'], Review, ContextType>;
  body?: Resolver<Scalars['String']['output'], Review, ContextType>;
  book?: Resolver<Book, Review, ContextType>;
  user?: Resolver<User, Review, ContextType>;
  createdAt?: Resolver<Scalars['DateTime']['output'], Review, ContextType>;
};

export type RatingResolvers<ContextType = GraphQLContext> = {
  id?: Resolver<Scalars['ID']['output'], Rating, ContextType>;
  score?: Resolver<Scalars['Int']['output'], Rating, ContextType>;
  book?: Resolver<Book, Rating, ContextType>;
  user?: Resolver<User, Rating, ContextType>;
  createdAt?: Resolver<Scalars['DateTime']['output'], Rating, ContextType>;
};

export type ChatMessageResolvers<ContextType = GraphQLContext> = {
  id?: Resolver<Scalars['ID']['output'], ChatMessage, ContextType>;
  message?: Resolver<Scalars['String']['output'], ChatMessage, ContextType>;
  book?: Resolver<Book, ChatMessage, ContextType>;
  user?: Resolver<User, ChatMessage, ContextType>;
  createdAt?: Resolver<Scalars['DateTime']['output'], ChatMessage, ContextType>;
};

export type Resolvers<ContextType = GraphQLContext> = {
  DateTime?: GraphQLScalarType | DateTimeScalarConfig;
  Query?: QueryResolvers<ContextType>;
  Mutation?: MutationResolvers<ContextType>;
  Subscription?: SubscriptionResolvers<ContextType>;
  User?: UserResolvers<ContextType>;
  Book?: BookResolvers<ContextType>;
  Review?: ReviewResolvers<ContextType>;
  Rating?: RatingResolvers<ContextType>;
  ChatMessage?: ChatMessageResolvers<ContextType>;
};
