/* eslint-disable */
// This file is generated by GraphQL Code Generator. Do not edit directly.
export type Maybe<T> = T | null;
export type InputMaybe<T> = Maybe<T>;
export type Exact<T extends { [key: string]: unknown }> = { [K in keyof T]: T[K] };
export type MakeOptional<T, K extends keyof T> = Omit<T, K> & { [SubKey in K]?: Maybe<T[SubKey]> };
export type MakeMaybe<T, K extends keyof T> = Omit<T, K> & { [SubKey in K]: Maybe<T[SubKey]> };
export type MakeEmpty<T extends { [key: string]: unknown }, K extends keyof T> = { [_ in K]?: never };
export type Incremental<T> = T | { [P in keyof T]?: P extends '__typename' | '$fragmentName' ? T[P] : never };

export type Scalars = {
  ID: { input: string; output: string };
  String: { input: string; output: string };
  Boolean: { input: boolean; output: boolean };
  Int: { input: number; output: number };
  Float: { input: number; output: number };
  DateTime: { input: string; output: string };
};

export type AddReviewInput = {
  bookId: Scalars['ID']['input'];
  body: Scalars['String']['input'];
  score?: InputMaybe<Scalars['Int']['input']>;
};

export type AuthPayload = {
  __typename?: 'AuthPayload';
  token: Scalars['String']['output'];
  user: User;
};

export type Book = {
  __typename?: 'Book';
  author: Scalars['String']['output'];
  averageRating?: Maybe<Scalars['Float']['output']>;
  coverUrl?: Maybe<Scalars['String']['output']>;
  createdAt: Scalars['DateTime']['output'];
  description: Scalars['String']['output'];
  genre: Scalars['String']['output'];
  id: Scalars['ID']['output'];
  owner: User;
  ratings: Array<Rating>;
  reviews: ReviewConnection;
  title: Scalars['String']['output'];
};

export type BookReviewsArgs = {
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Int']['input']>;
};

export type BookConnection = {
  __typename?: 'BookConnection';
  edges: Array<BookEdge>;
  pageInfo: PageInfo;
};

export type BookEdge = {
  __typename?: 'BookEdge';
  cursor: Scalars['String']['output'];
  node: Book;
};

export type ChatMessage = {
  __typename?: 'ChatMessage';
  book: Book;
  createdAt: Scalars['DateTime']['output'];
  id: Scalars['ID']['output'];
  message: Scalars['String']['output'];
  user: User;
};

export type ChatMessageConnection = {
  __typename?: 'ChatMessageConnection';
  edges: Array<ChatMessageEdge>;
  pageInfo: PageInfo;
};

export type ChatMessageEdge = {
  __typename?: 'ChatMessageEdge';
  cursor: Scalars['String']['output'];
  node: ChatMessage;
};

export type CreateBookInput = {
  author: Scalars['String']['input'];
  coverUrl?: InputMaybe<Scalars['String']['input']>;
  description: Scalars['String']['input'];
  genre: Scalars['String']['input'];
  title: Scalars['String']['input'];
};

export type LoginInput = {
  email: Scalars['String']['input'];
  password: Scalars['String']['input'];
};

export type PageInfo = {
  __typename?: 'PageInfo';
  endCursor?: Maybe<Scalars['String']['output']>;
  hasNextPage: Scalars['Boolean']['output'];
};

export type Rating = {
  __typename?: 'Rating';
  book: Book;
  createdAt: Scalars['DateTime']['output'];
  id: Scalars['ID']['output'];
  score: Scalars['Int']['output'];
  user: User;
};

export type RegisterInput = {
  email: Scalars['String']['input'];
  name: Scalars['String']['input'];
  password: Scalars['String']['input'];
};

export type Review = {
  __typename?: 'Review';
  body: Scalars['String']['output'];
  book: Book;
  createdAt: Scalars['DateTime']['output'];
  id: Scalars['ID']['output'];
  user: User;
};

export type ReviewConnection = {
  __typename?: 'ReviewConnection';
  edges: Array<ReviewEdge>;
  pageInfo: PageInfo;
};

export type ReviewEdge = {
  __typename?: 'ReviewEdge';
  cursor: Scalars['String']['output'];
  node: Review;
};

export type SendChatMessageInput = {
  bookId: Scalars['ID']['input'];
  message: Scalars['String']['input'];
};

export type User = {
  __typename?: 'User';
  avatarUrl?: Maybe<Scalars['String']['output']>;
  books: Array<Book>;
  createdAt: Scalars['DateTime']['output'];
  email: Scalars['String']['output'];
  id: Scalars['ID']['output'];
  name: Scalars['String']['output'];
};

export type UserFieldsFragment = { __typename?: 'User'; id: string; name: string; avatarUrl?: string | null };

export type RatingFieldsFragment = {
  __typename?: 'Rating';
  id: string;
  score: number;
  user: { __typename?: 'User'; id: string; name: string; avatarUrl?: string | null };
};

export type ReviewFieldsFragment = {
  __typename?: 'Review';
  id: string;
  body: string;
  createdAt: string;
  user: { __typename?: 'User'; id: string; name: string; avatarUrl?: string | null };
};

export type BookFieldsFragment = {
  __typename?: 'Book';
  id: string;
  title: string;
  author: string;
  description: string;
  genre: string;
  coverUrl?: string | null;
  averageRating?: number | null;
  owner: { __typename?: 'User'; id: string; name: string; avatarUrl?: string | null };
};

export type ChatMessageFieldsFragment = {
  __typename?: 'ChatMessage';
  id: string;
  message: string;
  createdAt: string;
  user: { __typename?: 'User'; id: string; name: string; avatarUrl?: string | null };
};

export type BooksQueryVariables = Exact<{
  first: Scalars['Int']['input'];
  after?: InputMaybe<Scalars['String']['input']>;
  search?: InputMaybe<Scalars['String']['input']>;
}>;

export type BooksQuery = {
  __typename?: 'Query';
  books: {
    __typename?: 'BookConnection';
    edges: Array<{
      __typename?: 'BookEdge';
      cursor: string;
      node: {
        __typename?: 'Book';
        id: string;
        title: string;
        author: string;
        description: string;
        genre: string;
        coverUrl?: string | null;
        averageRating?: number | null;
        owner: { __typename?: 'User'; id: string; name: string; avatarUrl?: string | null };
        reviews: {
          __typename?: 'ReviewConnection';
          edges: Array<{
            __typename?: 'ReviewEdge';
            node: {
              __typename?: 'Review';
              id: string;
              body: string;
              createdAt: string;
              user: { __typename?: 'User'; id: string; name: string; avatarUrl?: string | null };
            };
          }>;
        };
        ratings: Array<{ __typename?: 'Rating'; id: string; score: number }>;
      };
    }>;
    pageInfo: { __typename?: 'PageInfo'; endCursor?: string | null; hasNextPage: boolean };
  };
  recommendations?:
    | Array<{
        __typename?: 'Book';
        id: string;
        title: string;
        author: string;
        description: string;
        genre: string;
        coverUrl?: string | null;
        averageRating?: number | null;
        owner: { __typename?: 'User'; id: string; name: string; avatarUrl?: string | null };
      }>
    | null;
};

export type ChatMessagesQueryVariables = Exact<{
  bookId: Scalars['ID']['input'];
  first: Scalars['Int']['input'];
  after?: InputMaybe<Scalars['String']['input']>;
}>;

export type ChatMessagesQuery = {
  __typename?: 'Query';
  chatMessages: {
    __typename?: 'ChatMessageConnection';
    edges: Array<{
      __typename?: 'ChatMessageEdge';
      cursor: string;
      node: {
        __typename?: 'ChatMessage';
        id: string;
        message: string;
        createdAt: string;
        user: { __typename?: 'User'; id: string; name: string; avatarUrl?: string | null };
      };
    }>;
    pageInfo: { __typename?: 'PageInfo'; endCursor?: string | null; hasNextPage: boolean };
  };
};

export type LoginMutationVariables = Exact<{
  input: LoginInput;
}>;

export type LoginMutation = {
  __typename?: 'Mutation';
  login: { __typename?: 'AuthPayload'; token: string; user: { __typename?: 'User'; id: string; name: string; email: string } };
};

export type CreateBookMutationVariables = Exact<{
  input: CreateBookInput;
}>;

export type CreateBookMutation = {
  __typename?: 'Mutation';
  createBook: {
    __typename?: 'Book';
    id: string;
    title: string;
    author: string;
    description: string;
    genre: string;
    coverUrl?: string | null;
    averageRating?: number | null;
    owner: { __typename?: 'User'; id: string; name: string; avatarUrl?: string | null };
  };
};

export type AddReviewMutationVariables = Exact<{
  input: AddReviewInput;
}>;

export type AddReviewMutation = {
  __typename?: 'Mutation';
  addReview: {
    __typename?: 'Review';
    id: string;
    body: string;
    createdAt: string;
    user: { __typename?: 'User'; id: string; name: string; avatarUrl?: string | null };
  };
};

export type SendChatMessageMutationVariables = Exact<{
  input: SendChatMessageInput;
}>;

export type SendChatMessageMutation = {
  __typename?: 'Mutation';
  sendChatMessage: {
    __typename?: 'ChatMessage';
    id: string;
    message: string;
    createdAt: string;
    user: { __typename?: 'User'; id: string; name: string; avatarUrl?: string | null };
  };
};

export type ChatMessageAddedSubscriptionVariables = Exact<{
  bookId: Scalars['ID']['input'];
}>;

export type ChatMessageAddedSubscription = {
  __typename?: 'Subscription';
  chatMessageAdded: {
    __typename?: 'ChatMessage';
    id: string;
    message: string;
    createdAt: string;
    user: { __typename?: 'User'; id: string; name: string; avatarUrl?: string | null };
  };
};
